# Generated by Django 5.2.6 on 2025-09-29 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='PDF file uploaded by the user', upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the PDF was uploaded')),
                ('name', models.CharField(blank=True, help_text='Name of the uploaded PDF', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_query', models.TextField(help_text='The query asked by the user')),
                ('response', models.TextField(blank=True, help_text='The response provided by the system', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the query was made')),
                ('pdf', models.ForeignKey(help_text='PDF related to this query', on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='retrival.uploadedpdf')),
            ],
        ),
    ]
